#!/bin/sh

### BEGIN INIT INFO
# Provides:          docsflow
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Zigbee2mqtt application
# Description:  Zigbee2mqtt application
### END INIT INFO

case "$1" in
  start)
    echo "starting zigbee2mqtt"
    cd /opt/zigbee2mqtt
    npm start > /dev/null 2>&1 &
    exit 0
    ;;
  stop)
    echo "stopping zigbee2mqtt"
    pkill 'node'
    sleep 2
    exit 0
    ;;
esac

echo "unknown command $1"
exit 1